# Generated by Django 3.1.2 on 2021-11-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smashorpass', '0010_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
